### ISSUE TITLE
Read items do not sync from server

### ISSUE THREAD

**Issue by ardichoke** [hrk/tt-rss-newsplus-plugin#4]
I use tt-rss from multiple locations (desktop, laptop, phone, tablet). When I've read items elsewhere, the news+ plugin does not sync the state changes for any of the read articles. The only way I have found to get this to work is to clear the cache and then sync again.

**Comment by posledov** [comment]
```/var/www/rss # date; git pull
Tue Jan 19 11:20:58 EET 2016
Already up-to-date.```
api_newsplus plugin — 1.00
News+ — 2.0.2

step to reproduce:

1. fetch a new articles in news+ app, but not mark them as read
2. mark them as read in browser
3. update/sync an articles in news+ app

all articles, that have been marked as read in the browser, remains unread in the news+ app

however, if I mark an articles as read in a browser before they will be fetched in app, then everything is OK.

is it the problem of plugin or news+ application?

thanks.

p.s.: sory for my English

**Comment by hrk** [comment]
Step 3 works for me, I see the articles disappearing from the News+ app. I perform an update/sync directly from the main window/list with all the feeds.

**Comment by ardichoke** [comment]
I don't mean to be rude, but does any of this matter anymore? News+ seems to be a dead project. Hasn't been updated in over a year and the developer's website is dead.

@posledov I would suggest using the official Tiny Tiny RSS client at this point. It's not as pretty or full featured but at least it is still being developed and it works.

**Comment by hrk** [comment]
Well, I can only say that the app has been working fine for me and does everything I need it to do.. :)

**Comment by posledov** [comment]
> Step 3 works for me, I see the articles disappearing from the News+ app. I perform an update/sync directly from the main window/list with all the feeds.

> Well, I can only say that the app has been working fine for me and does everything I need it to do.. :)

Perfectly! These are exactly the words that every developer has to say when users tell him about the problems. Keep it up!

#WORKSFORME #FCKFF

**Comment by hrk** [comment]
Okay, let's try it again.

The issue is not with my plugin.

Thank you.

Good bye.

**Comment by AndreaGiardini** [comment]
@posledov Works for me as well... did you enable the "two way sync" from the app?
