### ISSUE TITLE
Plugin broken?

### ISSUE THREAD

**Issue by dertuxmalwieder** [hrk/tt-rss-newsplus-plugin#6]
Hi,

for some yet unknown reason this plug-in fails to log in on my TT-RSS git instance since about two weeks. It says "Could not login", even with valid credentials.

The log says:

> api/index.php:75	Cannot modify header information - headers already sent

Obviously, News+ gets headers which should not be there. The web version works fine.

Any ideas?

**Comment by hrk** [comment]
Plugin works fine here w/ latest tt-rss git pull and Play Store's News+.

Check your tt-rss installation to see if there are any modified files, especially with some extra whitespace (blank lines, space character, ...).

**Comment by dertuxmalwieder** [comment]
According to `git status` there are no changes.

**Comment by hrk** [comment]
Did you perform a git pull on the tt-rss installation? I updated it right now and then syncronized News+ with success.

**Comment by dertuxmalwieder** [comment]
Yes, I did, still no improvement. :/

**Comment by dertuxmalwieder** [comment]
By the way: The problem was that `always_populate_raw_post_data` (or something) was still "On", that sent a "Deprecated" warning before the header. Sorry - entirely my fault.

**Comment by hrk** [comment]
Cool :-)
