### ISSUE TITLE
Support PDO

### ISSUE THREAD

**Issue by PerfectSlayer** [hrk/tt-rss-newsplus-plugin#8]
Hi @hrk 

Due to the migration to PDO, the plug-in raise an error: `Legacy connection`.
I saw [on the community forum](https://discourse.tt-rss.org/t/pdo-is-coming-heres-what-you-need-to-know/689/84) you plan to port you add-on. Could you confirm this add-on will be maintained?
Do you need help for the port ? I also saw one commit to address the issue: https://github.com/schmidi/tt-rss-newsplus-plugin/commit/81242ba38fbe0056912b35b81d24422d99ccffe5 (I haven't tested it).

Thanks!

**Comment by hrk** [comment]
Sorry for the late reply. I incorporated @schmidi's changes in a new 6ab5b92 as I couldn't understand how to merge a fork. The code is now ready and has been tested to work.

**Comment by hrk** [comment]
Note: for people running an old instance there is a separate branch called pre-pdo. This seemed easier to me than managing two APIs at the same time.

**Comment by schmidi** [comment]
@hrk Thanks for including my changes. The plugin works and gives no warnings with the new PDO class, nevertheless I suggest to refactor the queries as prepare methods are not correctly used.
